# Generated by Django 6.1 on 2026-08-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='hitesh', max_length=255),
            preserve_default=False,
        ),
    ]
