# Generated by Django 6.1 on 2026-09-03 06:26

import first_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_alter_customuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=first_app.models.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
