# Generated by Django 6.1 on 2026-09-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_product_image_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
