# Generated by Django 6.1 on 2026-09-07 13:40

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_order_datetime_of_payment_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Seller', 'SELLER'), ('Customer', 'CUSTOMER')], default=[], max_length=100, null=True),
        ),
    ]
